### ISSUE TITLE
Search returning matches that don't match

### ISSUE THREAD

**Issue by matt454357** [brenkmanco/hackpdm#12]
This image shows that, under certain conditions, the search returns results that don't actually match (assuming AND connections between criteria).
- Property contains specified
- Checked Out to Me box is checked

![image](https://cloud.githubusercontent.com/assets/7604932/7760406/964810e8-ffd8-11e4-865d-6e1bcb6d77df.png)

@briggsj3, Do you have time to work on it?  I probably won't get to it until tomorrow.

**Comment by briggsj3** [comment]
I can't tell what isn't matching from the results.  Are some of the results
not actually checked out to you?  Or do some of them not have the specified
property?  Or, if all of them have a value for the specified property, do
any of the property values not match the requested value?

If I remember correctly, if a property value is text (not numeric, date, or
boolean), then a SQL LIKE syntax is used.  This might be making the
difference if the issue is the latter.

-JB

**Comment by matt454357** [comment]
Search criteria:
- Property "PartNum" contains "X0"
- "Checked Out to Me" = true

In the results, you can see a file named SWBrowser.mdb.  In the main window, you can see that SWBrowser.mdb has no properties assigned at all.

I would expect the query to come out something like this:

``` SQL
WHERE e.checkout_user=1003
AND vp.prop_id=9876
AND vp.text_value ILIKE '%X0%'
```

Maybe it has an OR somewhere?

**Comment by matt454357** [comment]
I tried searching without "Checked Out to Me" = true.  I got an error, but I believe this is from a different issue.

![image](https://cloud.githubusercontent.com/assets/7604932/7773898/9dcbe222-0064-11e5-909f-2197656a1025.png)

**Comment by matt454357** [comment]
Okay.  It looks like these two errors are related.  We seem to be missing the property id, like this:

``` SQL
AND vp.prop_id=9876
```

Or, we could do this:

``` SQL
LEFT JOIN hp_property ON hp_property AS p ON p.prop_id=vp.prop_id
...
AND p.prop_name='PartNum'
```

**Comment by briggsj3** [comment]
I found that same issue a few minutes ago and am fixing it now.  Will push
shortly.
-JB
